version: '0'

services:
 app1:
  build: .
  container_name: app1
  ports:
   - "3000:3000"
  environment:
   - MESSAGE=${MESSAGE}
 app2:
  container_name: app2
  build: .
  ports:
   - "3001:3000"
  environment: 
   - MESSAGE=${MESSAGE}
 app3:
  container_name: app3
  build: .
  ports:
   - "3002:3000"
  environment: 
   - MESSAGE=${MESSAGE}

 db:
  image: postgres:14
  container_name: db_postgres
  restart: always
  environment:
   - POSTGRES_PASSWORD=PASSWORD
   - POSTGRES_USER=YAIR
   - POSTGRES_DB=SEMANA2
  ports:
   - "5432:5432"
  volumes:
   - db_data:/var/lib/postgresql/data

volumes:
 db_data: